# server properties
server:
  port: 8083
# spring properties
spring:
  application:
    name: USER-SERVICE
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  file:
    path: './logs/logs'
    name: ${logging.file.path}/my-app.log
  level:
    org.springframework.web: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"